apiVersion: v1
kind: Namespace
metadata:
  name: omni-commerce
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: omni-commerce-config
  namespace: omni-commerce
data:
  KAFKA_BROKER: kafka:9092
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  PRODUCT_SERVICE_URL: http://product-service:3001
  ORDER_SERVICE_URL: http://order-service:3002
  PAYMENT_SERVICE_URL: http://payment-service:3003
---
apiVersion: v1
kind: Secret
metadata:
  name: omni-commerce-secrets
  namespace: omni-commerce
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  JWT_SECRET: super_secret_key
